# Generated by Django 3.2.2 on 2021-05-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detalles_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.CharField(max_length=20)),
                ('cantidad', models.FloatField(max_length=20)),
                ('valorTotal', models.FloatField(max_length=20)),
                ('valorIva', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField(max_length=20)),
            ],
        ),
    ]
