# Generated by Django 3.2.2 on 2021-05-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_productos',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_api.productos'),
        ),
    ]
