# Generated by Django 3.2.2 on 2021-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_api', '0002_alter_detalles_productos_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
