# Generated by Django 3.2.2 on 2021-05-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_api', '0004_auto_20210510_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio_currency',
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(max_length=11),
        ),
    ]
