# Generated by Django 3.2.2 on 2021-05-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_api', '0005_auto_20210510_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(max_length=20),
        ),
    ]
